FROM eclipse-temurin:17-jdk-focal
WORKDIR /app
ENV AP_PORT=8080
EXPOSE $APP_PORT
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:go-offline
 
COPY src ./src
 
CMD ["./mvnw", "spring-boot:run", "-Dserver.port=$APP_PORT"]
