server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 5MB # Cấu hình kích thước tối đa cho một file được upload (5MB ở đây)
      max-request-size: 10MB # Cấu hình kích thước tối đa cho một request chứa nhiều file
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/fc_management?createDatabaseIfNotExist=true
    username: root
    password: NguyenVanSuong@2001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  jackson:
    default-property-inclusion: always
media:
  saver:
    active: local
    local:
      absolute-path: "D:\\edu\\fc-management\\fc-management-backend\\upload"
      host: http://localhost:${server.port}/${server.servlet.context-path}/resources
logging:
  ignores-path:
    - "/api/resources/**"