server:
  port: 8080
  servlet:
    context-path: /api

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/fc_management
    username: root
    password: Tinh0501@@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

database:
  dump:
    path: "classpath:/db_dump/"
  con_job: 0 37 10 * * ?

build:
  version: "1.0"