spring:
  config:
    import:
      - "application_test.yml"
      - "application_prod.yml"
      - "application_dev.yml"
  profiles:
    active:
      - "dev"
media:
  img-path: "/image/"
  video-path: "/video/"