server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 5MB # Cấu hình kích thước tối đa cho một file được upload
      max-request-size: 10MB # Cấu hình kích thước tối đa cho một request chứa nhiều file
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/fc_management?createDatabaseIfNotExist=true
    username: root
    password: Tinh0501@@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false
  jackson:
    default-property-inclusion: always
  mvc:
    time-zone: "Asia/Ho_Chi_Minh"
  liquibase:
    user: root
    password: Tinh0501@@123
media:
  saver:
    active: local
    local:
      absolute-path: "D:\\EXAMPLE\\FC_MANAGEMENT\\BE\\fc-management-backend\\upload"
      host: http://localhost:${server.port}${server.servlet.context-path}/resources
logging:
  ignores-path:
    - "/api/resources/**"
security:
  cors:
    url: http://localhost:4200, https://tinhf0501.github.io
springdoc:
  api-docs:
    path: /api-docs #default url doc api http://localhost:8080/v3/api-docs/
  swagger-ui:
    path: /swagger-ui.html # default http://localhost:8080/swagger-ui.html
    operations-sorter: method # sắp xếp api theo http method
job:
  delete-resource:
    active: true
    time: 0/30 * * * * ?
  clean-resource:
    active: true
    time: 0/30 * * * * ?
