server:
  port: 8080
  servlet:
    context-path: /api

spring:
  servlet:
    multipart:
      max-file-size: 5MB # Cấu hình kích thước tối đa cho một file được upload (5MB ở đây)
      max-request-size: 10MB # Cấu hình kích thước tối đa cho một request chứa nhiều file
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/fc_management?createDatabaseIfNotExist=true
    username: root
    password: Tinh0501@@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

#database:
#  dump:
#    target_path: "classpath:/dump/"
#    absolute_path: "D:\\EXAMPLE\\FC_MANAGEMENT\\BE\\fc-management-backend\\dump\\"
#  job: 0 52 16 * * ?

media:
  absolute-path: "D:/EXAMPLE/FC_MANAGEMENT/BE/fc-management-backend/upload"
  member-path: "/member/avatar/"
  fc-img-path: "/fc/imgs/"
  fc-logo-path: "/fc/logo/"
  fc-video-path: "/fc/videos/"
file:
  save:
    type: "LOCAL"

build:
  version: "1.0"